name    'invernizzi-google_chrome'
version '0.1.0'
source ''
author 'Luca Invernizzi <invernizzi.l@gmail.com>'
license 'Apache License, Version 2.0'
summary 'Installs the latest google chrome'
description ''
project_page 'https://github.com/invernizzi/puppet-googlechrome'

dependency 'maestrodev/wget'
